### ISSUE TITLE
Sorting mechanism

### ISSUE THREAD

**Issue by davidbacter01** [HumanBrainProject/pyunicore#30]
Hello,
Is there a way that we could reliably sort the jobs ?
Thanks in advance!

**Comment by BerndSchuller** [comment]
hi!
The jobs should be  sorted in submission order (newest first). Due to a bug they are currently not, but will be once UNICORE 9.0.1 is deployed at the sites. Any other ordering has to be done by the client. Since getting properties for many jobs consumes time (and CPU/networking resources on the UNICORE server), I'd rather not implement any "automatic" ordering in the client library.
